root: '273421673'
bt_uin: '3555202423'
enable_webui_interaction: false
debug: false
github_proxy: null
check_ncatbot_update: false
skip_ncatbot_install_check: false
websocket_timeout: 15
napcat:
  ws_uri: ws://127.0.0.1:3002
  ws_token: y-6u8nt[nfuftYnE
  ws_listen_ip: localhost
  webui_uri: http://127.0.0.1:6099
  webui_token: a4ee53569810
  enable_webui: false
  check_napcat_update: false
  stop_napcat: false
  remote_mode: false
  report_self_message: false
  report_forward_message_detail: true
plugin:
  plugins_dir: plugins
  plugin_whitelist: []
  plugin_blacklist: []
  skip_plugin_load: false
