class HMMT:
    HMMT_ID = 273421673
    BOT_ID = 3555202423
    IMAGE_PATH = "F:\\oobabooga_windows\\lalafell\\"
    IMAGE_PATH1 = "F:\\oobabooga_windows\\test\\"
    ALICE_IMAGE_PATH = "data/image/alice/"
    SIR_PATH = "data/image/sir/"
    CHESHIRE_PATH = "data/image/cheshire/"
    DORO_PATH = "data/image/doro/"
    SONG_PATH = "data/mp3/song/"
    GUGU_PATH = "data/image/gugugu/"
    LALAFELL_KEYWORD1 = "母肥"
    LALAFELL_KEYWORD2 = "母肥 "
    ALICE_KEYWORD1 = "alice"
    ALICE_KEYWORD2 = "alice "
    LALAFELL_KEYWORD_SUBSTRING = 3
    ALICE_KEYWORD_SUBSTRING = 6
    BOBO_KEYWORD1 = "bobo"
    BOBO_KEYWORD2 = "啵啵"
    SAY_KEY = "说"
    CRAZY_KEY = "发病 "
    CRAZY_THURSDAY = "疯狂星期四"
    THE_MYSTERIES_OF_THE_UNIVERSE = "42"
    IMG_EAT_PATH = "data/image/eat_pic/"
    IMG_DRINK_PATH = "data/image/drink_pic/"
    BILIBILI_PATH = "data/image/bilibili/"
    DEFAULT_IMAGE_SCALE_SAVE_PATH = "data/image/scale"
    IMAGE_SCALE_PREFIX = "scale_"
    V_PATH = "data/image/vtuber/"
    USER_AGENT = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36"
    LALAFELL_GROUP_ID = 853963912
    HMMT_GROUP_ID = 1064163905