# 二次元综合
ERCIYUAN = {
    "图片一": {"triggers": ["图片一"], "id": "img1"},
    "图片二": {"triggers": ["图片二"], "id": "img2"},
    "竖屏壁纸": {"triggers": ["竖屏壁纸"], "id": "sjpic"},
    "横屏壁纸": {"triggers": ["横屏壁纸"], "id": "pc"},
    "黑丝": {"triggers": ["黑丝"], "id": "acghs"},
    "白丝": {"triggers": ["白丝"], "id": "acgbs"},
    # "兽耳": {"triggers": ["兽耳"], "id": "kemonomimi"},
    "白毛": {"triggers": ["白毛"], "id": "yin"},
    "星空": {"triggers": ["星空"], "id": "xingk"},
    "loli": {"triggers": ["loli"], "id": "loli"},
}

# 三次元综合
SANCIYUAN = {
    "小姐姐": {"triggers": ["小姐姐"], "id": "xjj"},
    "高清风景壁纸": {"triggers": ["高清风景壁纸"], "id": "gqbz"},
    "猫星人": {"triggers": ["猫星人"], "id": "cat"},
}

# 虚拟主播系列
VTB = {
    "小鲨鱼": {"triggers": ["小鲨鱼", "Gawr"], "id": "gawr-gura"},
    "雪花菈米": {"triggers": ["雪花菈米"], "id": "yukihana"},
    "夏色祭": {"triggers": ["夏色祭"], "id": "natsuiro"},
    "润羽露西娅": {"triggers": ["润羽露西娅"], "id": "uruha-rushia"},
    "花园Serena": {"triggers": ["花园Serena"], "id": "hanazono-serena"},
    "笹木咲": {"triggers": ["笹木咲"], "id": "sasaki-saku"},
    "角卷绵芽": {"triggers": ["角卷绵芽"], "id": "tsunomaki-watame"},
    "常暗永远": {"triggers": ["常暗永远"], "id": "tokoyami-towa"},
    "天宫心": {"triggers": ["天宫心"], "id": "amamiya-kokoro"},
    "兔田佩克菈": {"triggers": ["兔田佩克菈"], "id": "usada-pekora"},
    "一伊那尔栖": {"triggers": ["一伊那尔栖"], "id": "ninomae"},
    "大神澪": {"triggers": ["大神澪"], "id": "ookami-mio"},
    "星川莎拉": {"triggers": ["星川莎拉"], "id": "sara-hoshikawa"},
    "樱巫女": {"triggers": ["樱巫女"], "id": "sakura-miko"},
    "木口EN": {"triggers": ["木口EN", "HoloEN"], "id": "holoen"},
    "绊爱": {"triggers": ["绊爱", "Kizuna"], "id": "kizunaai"},
    "神乐七奈": {"triggers": ["神乐七奈"], "id": "kagura-nana"},
    "神乐Mea": {"triggers": ["神乐mea", "mea"], "id": "kagura-mea"},
    "白上吹雪": {"triggers": ["白上吹雪"], "id": "fubuki"},
    "戌神沁音": {"triggers": ["戌神沁音"], "id": "inugami-korone"},
    "阿夸": {"triggers": ["阿夸", "Aqua", "aqua"], "id": "aqua"},
    "猫宫日向": {"triggers": ["猫宫日向"], "id": "nekomiya-hinata"},
}

# 角色系列
CHARACTERS = {
    "猫羽雫": {"triggers": ["猫羽雫"], "id": "myn"},
    "樱岛麻衣": {"triggers": ["樱岛麻衣"], "id": "ydmy"},
    "初音未来": {"triggers": ["初音未来", "初音", "Miku"], "id": "miku"},
    "洛天依": {"triggers": ["洛天依"], "id": "tianyi"},
    "五更琉璃": {"triggers": ["五更琉璃"], "id": "gokou-ruri"},
    "椎名真白": {"triggers": ["椎名真白"], "id": "mashiro"},
    "鹿乃": {"triggers": ["鹿乃"], "id": "kano"},
    "Saber": {"triggers": ["Saber"], "id": "saber"},
    "四系乃": {"triggers": ["四系乃"], "id": "yoshino"},
    "见崎鸣": {"triggers": ["见崎鸣"], "id": "misakimei"},
    "阿卡林": {"triggers": ["阿卡林"], "id": "akari"},
    "康娜": {"triggers": ["康娜"], "id": "kanna"},
    "喵帕斯": {"triggers": ["喵帕斯"], "id": "miaops"},
    "妮姆芙": {"triggers": ["妮姆芙"], "id": "nymph"},
    "诺艾尔": {"triggers": ["诺艾尔"], "id": "noel"},
    "时崎狂三": {"triggers": ["时崎狂三"], "id": "kurumi"},
    "薇尔莉特": {"triggers": ["薇尔莉特"], "id": "violet"},
    "忍野忍": {"triggers": ["忍野忍"], "id": "shinobu"},
    "风见一姬": {"triggers": ["风见一姬"], "id": "kazuki"},
    "伊莉雅": {"triggers": ["伊莉雅"], "id": "iliya"},
    "碧翠丝": {"triggers": ["碧翠丝"], "id": "beatrice"},
    "土间埋": {"triggers": ["土间埋", "小埋"], "id": "umr"},
    "雷姆": {"triggers": ["雷姆"], "id": "rem"},
    "阿波连": {"triggers": ["阿波连"], "id": "aharen"},
    "国家队02": {"triggers": ["02", "国家队"], "id": "02"},
    "阿尼亚": {"triggers": ["阿尼亚"], "id": "aniya"},
    "高木": {"triggers": ["高木"], "id": "takagi"},
    "御坂美琴": {"triggers": ["御坂美琴", "炮姐"], "id": "misaka-mikoto"},
    "约尔": {"triggers": ["约尔"], "id": "yor"},
    "水原千鹤": {"triggers": ["水原千鹤", "千鹤"], "id": "mizuhara"},
    "矢泽妮可": {"triggers": ["矢泽妮可", "妮可"], "id": "nico"},
    "唐可可": {
        "triggers": [
            "唐可可",
        ],
        "id": "tangkk",
    },
    "千反田爱瑠": {"triggers": ["千反田爱瑠"], "id": "eru"},
    "亚丝娜": {"triggers": ["亚丝娜"], "id": "asuna"},
    "香风智乃": {"triggers": ["香风智乃"], "id": "chiro"},
    "凯露": {"triggers": ["凯露"], "id": "karyl"},
    "灰原哀": {"triggers": ["灰原哀"], "id": "haibara"},
    "雏鹤爱": {"triggers": ["雏鹤爱"], "id": "hinatsuru"},
    "志摩凛": {"triggers": ["志摩凛"], "id": "shimarin"},
    "小鸟游六花": {"triggers": ["小鸟游六花", "六花"], "id": "rikka"},
    "加藤惠": {"triggers": ["加藤惠"], "id": "katoumegumi"},
    "雪之下雪乃": {"triggers": ["雪之下雪乃", "雪乃"], "id": "yukino"},
    "谢丝塔": {"triggers": ["谢丝塔"], "id": "siesta"},
    "早坂爱": {"triggers": ["早坂爱"], "id": "hayasakaai"},
    "四宫辉夜": {"triggers": ["四宫辉夜", "辉夜"], "id": "kaguya"},
    "凉宫春日": {"triggers": ["凉宫春日", "团长"], "id": "haruhi"},
    "藤原千花": {"triggers": ["藤原千花"], "id": "chika"},
    "祢豆子": {"triggers": ["祢豆子"], "id": "nezuko"},
    "小野寺小咲": {"triggers": ["小野寺小咲"], "id": "onoderaoosaki"},
    "中野三玖": {"triggers": ["中野三玖", "三玖"], "id": "nakanomiku"},
    "伊蕾娜": {"triggers": ["伊蕾娜"], "id": "elaina"},
    "佐天泪子": {"triggers": ["佐天泪子", "泪子"], "id": "ruiko"},
    "白井黑子": {"triggers": ["白井黑子", "黑子"], "id": "kuroko"},
    "泉此方": {"triggers": ["泉此方"], "id": "konata"},
    "白银圭": {"triggers": ["白银圭"], "id": "shiroganekei"},
    "伊井野弥子": {"triggers": ["伊井野弥子"], "id": "linomiko"},
    "立华奏": {"triggers": ["立华奏"], "id": "kanade"},
    "喜多川海梦": {"triggers": ["喜多川海梦"], "id": "kitagawa-marin"},
    "熊污女": {"triggers": ["熊污女"], "id": "amayadori-machi"},
    "牧濑红莉栖": {"triggers": ["牧濑红莉栖", "助手"], "id": "makise-kurisu"},
    "艾拉": {"triggers": ["艾拉"], "id": "lsla"},
    "蝶祈": {"triggers": ["蝶祈"], "id": "yuzuriha-inori"},
    "伊卡洛斯": {"triggers": ["伊卡洛斯"], "id": "uranus-queen"},
    "八寻宁宁": {"triggers": ["八寻宁宁", "宁宁"], "id": "yashiro-nene"},
    "菲洛": {"triggers": ["菲洛"], "id": "filo"},
    "食蜂操祈": {"triggers": ["食蜂操祈"], "id": "shokuho-isaki"},
    "我妻由乃": {"triggers": ["我妻由乃"], "id": "gasai-yuno"},
    "长瀞同学": {"triggers": ["长瀞同学"], "id": "nagatoro-hayase"},
    "蜘蛛子": {"triggers": ["蜘蛛子"], "id": "noname-kumo"},
    "和泉纱雾": {"triggers": ["和泉纱雾"], "id": "izumi-sagiri"},
    "栗山未来": {"triggers": ["栗山未来"], "id": "kuriyama-mirai"},
    "奈亚子": {"triggers": ["奈亚子"], "id": "nyaruko"},
    "沙优": {"triggers": ["沙优"], "id": "ogiwara-sayu"},
    "维包子": {"triggers": ["维包子"], "id": "blois"},
    "摘希": {"triggers": ["摘希"], "id": "miniwa-tsumiki"},
}

# 游戏系列
GAMES = {
    "原神": {"triggers": ["原神", "op"], "id": "ys"},
    "明日方舟": {"triggers": ["明日方舟"], "id": "mrfz"},
    "碧蓝航线": {"triggers": ["碧蓝航线"], "id": "blhx"},
    "车万": {"triggers": ["车万", "东方"], "id": "dongf"},
    "碧蓝档案": {"triggers": ["碧蓝档案"], "id": "blda"},
    "缘之空": {"triggers": ["缘之空"], "id": "yzk"},
    "少女前线": {"triggers": ["少女前线", "少前"], "id": "snqx"},
    "崩坏三": {"triggers": ["崩坏三", "崩三"], "id": "bh3"},
}

# 动漫系列
ANIME = {
    "赛马娘": {"triggers": ["赛马娘"], "id": "saima"},
    "RE0": {"triggers": ["RE0", "从零开始"], "id": "re0"},
    "SAO": {"triggers": ["SAO", "刀剑神域"], "id": "sao"},
    "妖精的尾巴": {"triggers": ["妖精的尾巴", "妖尾"], "id": "yaowei"},
    "鬼灭之刃": {"triggers": ["鬼灭之刃", "鬼灭"], "id": "gmzr"},
    "五等分的花嫁": {"triggers": ["五等分的花嫁"], "id": "5huajia"},
    "冰菓": {"triggers": ["冰菓"], "id": "bingg"},
    "你的名字": {"triggers": ["你的名字"], "id": "kiminame"},
    "公主连接": {"triggers": ["公主连接", "公主链接"], "id": "gongzhulj"},
    "间谍过家家": {"triggers": ["间谍过家家"], "id": "spyfamily"},
    "摇曳露营": {"triggers": ["摇曳露营"], "id": "camp"},
    "摇曳百合": {"triggers": ["摇曳百合"], "id": "yuruyuri"},
    "天使降临到我身边": {"triggers": ["天使降临到我身边"], "id": "miyone"},
    "我们无法一起学习": {"triggers": ["我们无法一起学习"], "id": "xuebulai"},
    "悠哉日常大王": {"triggers": ["悠哉日常大王"], "id": "nobiyori"},
    "黄金拼图": {"triggers": ["黄金拼图"], "id": "kin-iro-mosaic"},
    "转生恶役大小姐": {"triggers": ["转生恶役大小姐"], "id": "flag-ojousama"},
    "崛与宫村": {"triggers": ["崛与宫村", "宫村"], "id": "hori-to-miyamura"},
    "路人女主": {"triggers": ["路人女主", "路人"], "id": "saenai-heroine"},
    "喜欢本大爷竟然就你一个": {
        "triggers": ["喜欢本大爷竟然就你一个"],
        "id": "mydcy",
    },
    "高原魔女": {"triggers": ["高原魔女"], "id": "slime-300"},
    "幼妻狐仙": {"triggers": ["幼妻狐仙"], "id": "fox-senko"},
    "游戏王": {"triggers": ["游戏王"], "id": "yu-gi-oh"},
    "莉可丽丝": {"triggers": ["莉可丽丝", "Lycoris"], "id": "lycoris-recoil"},
    "斩赤红之瞳": {"triggers": ["斩赤红之瞳", "赤瞳"], "id": "akame-ga-kill"},
    "Fgo": {"triggers": ["FGO", "命运冠位指定"], "id": "fgo"},
    "轻音": {"triggers": ["轻音", "K-ON"], "id": "k-on"},
    "Lovelive": {"triggers": ["Lovelive", "LL"], "id": "lovelive"},
    "Overlord": {"triggers": ["Overlord", "骨王"], "id": "overlord"},
    "变态王子与不笑猫": {
        "triggers": ["变态王子与不笑猫", "不笑猫"],
        "id": "hentaiandneko",
    },
    "不正经魔术师": {"triggers": ["不正经魔术师", "魔术师"], "id": "majutsu-koushi"},
    "空之境界": {"triggers": ["空之境界"], "id": "kara-no-kyoukai"},
    "小林家的龙女仆": {
        "triggers": ["小林家的龙女仆", "龙女仆"],
        "id": "kobayashi-no-dragon",
    },
    "龙与虎": {"triggers": ["龙与虎", "龙虎"], "id": "toradora"},
    "关于我转生变成史莱姆这件事": {
        "triggers": ["关于我转生变成史莱姆这件事", "史莱姆"],
        "id": "tensei-slime",
    },
    "未闻花名": {"triggers": ["未闻花名"], "id": "hana-no-amae"},
    "乌贼娘": {"triggers": ["乌贼娘"], "id": "ika-usume"},
    "小老师": {"triggers": ["小老师"], "id": "celia-claire"},
    "熊熊勇闯异世界": {"triggers": ["熊熊勇闯异世界"], "id": "kuma-bear"},
    "为美好的世界献上祝福": {
        "triggers": ["为美好的世界献上祝福", "素晴"],
        "id": "sekai-shukufuku",
    },
}

# 表情包系列
EMOJI = {
    "二次元表情包": {"triggers": ["二次元表情包"], "id": "bqb"},
    "甘城猫猫": {"triggers": ["甘城猫猫"], "id": "gcmm"},
    "MC酱": {"triggers": ["MC酱", "MC"], "id": "mc"},
    "kemomimi兽耳酱": {"triggers": ["kemomimi兽耳酱", "兽耳酱"], "id": "kemomimi"},
    "三次元猫猫": {"triggers": ["三次元猫猫"], "id": "miao"},
    "阿夸表情包": {"triggers": ["阿夸表情包"], "id": "akqa"},
    "柴郡猫猫": {"triggers": ["柴郡猫猫"], "id": "cheshire"},
    "猫猫虫咖波": {"triggers": ["猫猫虫咖波", "咖波"], "id": "capoo"},
    "塞西莉亚黑白": {"triggers": ["塞西莉亚黑白"], "id": "ceciliabqb"},
    "塞西莉亚": {"triggers": ["塞西莉亚"], "id": "cecilia"},
    "龙图": {"triggers": ["龙图"], "id": "longtu"},
    "罗翔": {"triggers": ["罗翔"], "id": "luox"},
    "滑稽": {"triggers": ["滑稽"], "id": "huaji"},
    "熊猫头": {"triggers": ["熊猫头"], "id": "pand"},
    "同福客栈": {"triggers": ["同福客栈"], "id": "tfkz"},
    "原神表情包": {"triggers": ["原神表情包"], "id": "ysbqb"},
    "北方酱": {"triggers": ["北方酱"], "id": "beifang"},
    "柯南": {"triggers": ["柯南"], "id": "kenan"},
    "猫和老鼠": {"triggers": ["猫和老鼠"], "id": "tomandjerry"},
    "小白人": {"triggers": ["小白人"], "id": "whitevillain"},
    "小婳": {"triggers": ["小婳"], "id": "xiaohua"},
    "商业头盔": {"triggers": ["商业头盔"], "id": "toukui"},
    "牢饭降临到我身边": {"triggers": ["牢饭降临到我身边", "牢饭"], "id": "laofan"},
    "狗妈": {"triggers": ["狗妈"], "id": "goum"},
    "索菲": {"triggers": ["索菲"], "id": "sofei"},
    "滑稽嘤嘤嘤": {"triggers": ["滑稽嘤嘤嘤"], "id": "yingyy"},
    "草莓果酱": {"triggers": ["草莓果酱"], "id": "caomeiguo"},
    "和泉纱雾表情包": {"triggers": ["和泉纱雾表情包"], "id": "shawu"},
}

# 合并所有命令
COMMANDS = {
    **ERCIYUAN,
    **SANCIYUAN,
    **VTB,
    **CHARACTERS,
    **GAMES,
    **ANIME,
    **EMOJI,
}

# 分类名称映射
CATEGORY_NAMES = {
    "ERCIYUAN": "二次元综合",
    "SANCIYUAN": "三次元综合",
    "VTB": "虚拟主播系列",
    "CHARACTERS": "角色系列",
    "GAMES": "游戏系列",
    "ANIME": "动漫系列",
    "EMOJI": "表情包系列",
}

# 分类命令映射
CATEGORY_COMMANDS = {
    "ERCIYUAN": ERCIYUAN,
    "SANCIYUAN": SANCIYUAN,
    "VTB": VTB,
    "CHARACTERS": CHARACTERS,
    "GAMES": GAMES,
    "ANIME": ANIME,
    "EMOJI": EMOJI,
}
