# This workflow will upload a Python Package using Twine when a release is created
 # For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries
 
 # This workflow uses actions that are not certified by GitHub.
 # They are provided by a third-party and are governed by
 # separate terms of service, privacy policy, and support
 # documentation.
 
 name: Upload Python Package
 
 on:
   push:
     branches:
       - main  # 指定触发的分支，根据实际情况修改
     paths:
       - "ncatbot/__init__.py"  # 只有当 __init__.py 文件发生变化时触发
   workflow_dispatch:  # 允许手动触发
 
 permissions:
   contents: read
 
 jobs:
   build-and-publish:
     runs-on: ubuntu-latest
 
     steps:
       - name: Checkout code
         uses: actions/checkout@v2
 
       - name: Set up Python
         uses: actions/setup-python@v2
         with:
           python-version: '3.x'  # 可以根据需要修改为具体的 Python 版本
 
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
           pip install setuptools wheel twine  # 安装打包和发布工具
 
       - name: Build the package
         run: |
           python setup.py sdist bdist_wheel  # 创建包
 
       - name: Upload the package to PyPI
         env:
           PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
         run: |
           twine upload dist/* -u __token__ -p $PYPI_TOKEN  # 使用 Twine 发布包
